[tool.poetry]
name = "aegis"
version = "0.1.0"
description = "Autonomous Embedded-Graph Intrusion Sentinel"
authors = ["johnno1011 <jonathan@intellium.ai>", "jacksmithy1 <jack.smith@intellium.ai>", "nifets.ai <stefan@intellium.ai>"]
readme = "README.md"
packages = [{include = "aegis", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
primaite = { git = "https://github.com/intellium-ai/primate.git", tag = "v1.0.0", extras= ["dev"] }


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
